import type { ExpoConfig } from '@expo/config';
import 'dotenv/config';

type FirebaseEnv = {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
  measurementId?: string;
};

type GoogleEnv = {
  webClientId: string;
  iosClientId: string;
  androidClientId: string;
};

const readEnv = (
  names: string[],
  options?: { optional?: boolean }
): string | undefined => {
  for (const name of names) {
    const value = process.env[name];
    if (typeof value === 'string' && value.trim().length > 0) {
      return value.trim();
    }
  }

  if (options?.optional) {
    return undefined;
  }

  const label = names.join(' or ');
  throw new Error(
    `[app.config] Missing required env var: ${label}. ` +
    `Copy .env.example to .env and set these values before starting Expo.`
  );
};

const firebase: FirebaseEnv = {
  apiKey: readEnv(['EXPO_PUBLIC_FIREBASE_API_KEY'])!,
  authDomain: readEnv(['EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN'])!,
  projectId: readEnv(['EXPO_PUBLIC_FIREBASE_PROJECT_ID'])!,
  storageBucket: readEnv(['EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET'])!,
  messagingSenderId: readEnv(['EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'])!,
  appId: readEnv(['EXPO_PUBLIC_FIREBASE_APP_ID'])!,
  measurementId: readEnv(['EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID'], { optional: true }),
};

const google: GoogleEnv = {
  webClientId: readEnv(
    ['EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID', 'EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID']
  )!,
  iosClientId: readEnv(['EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID'])!,
  androidClientId: readEnv(['EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID'])!,
};
const iosGoogleRedirectScheme = google.iosClientId.endsWith('.apps.googleusercontent.com')
  ? `com.googleusercontent.apps.${google.iosClientId.slice(0, -'.apps.googleusercontent.com'.length)}`
  : undefined;

const googleMapsApiKey = readEnv(['EXPO_PUBLIC_GOOGLE_MAPS_API_KEY'], { optional: true });
const iosPushNotificationsEnabled = true;

const config = {
  name: 'ManaSplit',
  slug: 'SplitCircle',
  version: '1.0.2',
  owner: 'chanikya6163',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  scheme: iosGoogleRedirectScheme ? ['splitcircle', iosGoogleRedirectScheme] : 'splitcircle',
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#FBF7F0',
  },
  notification: {
    color: '#E8A13D',
    iosDisplayInForeground: true,
  },
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.splitcircle.app',
    backgroundColor: '#FBF7F0',
    icon: {
      light: './assets/icon.png',
      dark: './assets/icon-dark.png',
      tinted: './assets/icon-tinted.png',
    },
    // Documentation parity with ios/SplitCircle/SplitCircle.entitlements (doc 27) —
    // this repo's ios/ is hand-maintained, not regenerated by `expo prebuild`, so
    // the entitlements file is what actually takes effect; this flag matters only
    // if this project ever goes back through prebuild.
    usesAppleSignIn: true,
    entitlements: {
      'aps-environment': 'production',
    },
    infoPlist: {
      CFBundleDisplayName: 'ManaSplit',
      CFBundleName: 'ManaSplit',
      ITSAppUsesNonExemptEncryption: false,
      NSPhotoLibraryUsageDescription: 'ManaSplit uses your photo library so you can choose photos and videos to send in chats, attach receipt photos to expenses, or set profile, group, and chat wallpaper images. For example, choose a dinner receipt to add to a shared expense.',
      NSCameraUsageDescription: 'ManaSplit uses your camera for video calls, taking photos to send in chats, and scanning receipts. For example, photograph a dinner receipt to add it to a shared expense.',
      NSMicrophoneUsageDescription: 'ManaSplit uses your microphone for voice and video calls and voice messages. For example, record a voice message to send in a group chat.',
      NSLocationWhenInUseUsageDescription: 'ManaSplit uses your location while you choose a place to share in a chat. For example, select your current location and send its map pin to a group.',
      NSFaceIDUsageDescription: 'ManaSplit uses Face ID to unlock protected chats and privacy settings. For example, confirm it is you before opening a locked chat.',
      NSLocalNetworkUsageDescription: 'ManaSplit uses your local network to find trusted nearby contacts and exchange messages when the internet is unavailable. For example, send a message to a paired device on the same Wi-Fi network.',
      NSBluetoothAlwaysUsageDescription: 'ManaSplit uses Bluetooth to connect with trusted nearby devices for offline messaging. For example, exchange a message with a paired phone when the internet is unavailable.',
      NSBonjourServices: ['_manasplit-mesh._tcp'],
      // Donated by the splitcircle-ai native module after an AI ask, so iOS can
      // surface "Ask SplitCircle" in Spotlight / Siri Suggestions.
      NSUserActivityTypes: ['com.splitcircle.ask-ai'],
      UIBackgroundModes: iosPushNotificationsEnabled
        ? ['audio', 'fetch', 'remote-notification', 'voip']
        : ['audio', 'fetch', 'voip'],
    },
  },
  android: {
    package: 'com.splitcircle.app',
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      monochromeImage: './assets/adaptive-icon-monochrome.png',
      backgroundColor: '#2A0B40',
    },
    predictiveBackGestureEnabled: false,
    permissions: [
      'CAMERA',
      'RECORD_AUDIO',
      'READ_MEDIA_IMAGES',
      'READ_MEDIA_VIDEO',
      'READ_MEDIA_AUDIO',
      'VIBRATE',
      'WAKE_LOCK',
      'FOREGROUND_SERVICE',
      'FOREGROUND_SERVICE_MEDIA_PLAYBACK',
      'FOREGROUND_SERVICE_MICROPHONE',
      'FOREGROUND_SERVICE_CAMERA',
      'com.android.vending.BILLING',
      'ACCESS_COARSE_LOCATION',
      'ACCESS_FINE_LOCATION',
      'com.google.android.c2dm.permission.RECEIVE',
    ],
    config: {
      googleMaps: {
        apiKey: googleMapsApiKey,
      },
    },
  },
  web: {
    favicon: './assets/favicon.png',
  },
  plugins: [
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        resizeMode: 'contain',
        imageWidth: 112,
        backgroundColor: '#FBF7F0',
        dark: {
          image: './assets/splash-icon-dark.png',
          backgroundColor: '#2A0B40',
        },
      },
    ],
    'expo-font',
    'expo-secure-store',
    'expo-web-browser',
    'expo-sqlite',
    'expo-iap',
    [
      'expo-notifications',
      {
        icon: './assets/notification-icon.png',
        color: '#E8A13D',
      },
    ],
    ['expo-audio', { enableBackgroundPlayback: true }],
    'expo-sharing',
    ['expo-video', { supportsBackgroundPlayback: true }],
    [
      'expo-location',
      {
        locationWhenInUsePermission: 'ManaSplit uses your location while you choose a place to share in a chat. For example, select your current location and send its map pin to a group.',
        isAndroidBackgroundLocationEnabled: false,
        isAndroidForegroundServiceEnabled: false,
        isIosBackgroundLocationEnabled: false,
      },
    ],
    ['expo-build-properties', { android: { minSdkVersion: 24 } }],
    '@livekit/react-native-expo-plugin',
    'react-native-compressor',
  ],
  extra: {
    eas: {
      projectId: '5050e81d-9b1b-4f2b-bc3a-abc457137122',
    },
    firebase,
    google,
  },
} as ExpoConfig;

export default config;
