export const ROUTES = {
  AUTH: {
    SIGN_IN: 'SignIn',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'ForgotPassword',
  },
  APP: {
    ROOT: 'Root',
    HOME: 'Home',
    GROUPS_TAB: 'ExpensesTab',
    GROUPS: 'Expenses',
    GROUP_DETAILS: 'GroupDetails',
    GROUP_INFO: 'GroupInfo',
    ADD_EXPENSE: 'AddExpense',
    SETTLEMENTS: 'Settlements',
    FRIENDS: 'Friends',
    FRIEND_INFO: 'FriendInfo',
    CHAT_TAB: 'ChatTab',
    CHAT: 'Chat',
    GROUP_CHAT: 'GroupChat',
    MESSAGE_INFO: 'MessageInfo',
    SEARCH_TAB: 'SearchTab',
    /** Unified app-wide search screen. Reachable as a TAB on Android. On iOS search is
     *  now the native UISearchController on each list screen (see
     *  headerSearchBarOptions in GroupListScreen), so this route is currently only an
     *  Android/global fallback — no iOS entry point. */
    SEARCH: 'Search',
    CALLS_TAB: 'CallsTab',
    CALLS: 'Calls',
    CALL_INFO: 'CallInfo',
    CALL_DETAIL: 'CallDetail',
    EXPENSE_DETAILS: 'ExpenseDetails',
    RECURRING_BILLS: 'RecurringBills',
    GROUP_STATS: 'GroupStats',
    PERSONAL_STATS: 'PersonalStats',
    ASK_AI: 'AskAi',
    SETTINGS: 'Settings',
    NOTIFICATION_SETTINGS: 'NotificationSettings',
    OFFLINE_SYNC: 'OfflineSync',
    AI_INDEX: 'AiIndex',
    PROFILE: 'Profile',
    CHAT_MEDIA_GALLERY: 'ChatMediaGallery',
    FILE_PREVIEW: 'FilePreview',
    STARRED_MESSAGES: 'StarredMessages',
    ARCHIVED_CHATS: 'ArchivedChats',
    LOCKED_CHATS: 'LockedChats',
    ARCHIVED_GROUPS: 'ArchivedGroups',
  },
} as const;
