export const ROUTES = {
  AUTH: {
    SIGN_IN: 'SignIn',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'ForgotPassword',
  },
  APP: {
    ROOT: 'Root',
    HOME: 'Home',
    GROUPS_TAB: 'ExpensesTab',
    GROUPS: 'Expenses',
    GROUP_DETAILS: 'GroupDetails',
    GROUP_INFO: 'GroupInfo',
    ADD_EXPENSE: 'AddExpense',
    SETTLEMENTS: 'Settlements',
    FRIENDS: 'Friends',
    FRIEND_INFO: 'FriendInfo',
    CHAT_TAB: 'ChatTab',
    CHAT: 'Chat',
    GROUP_CHAT: 'GroupChat',
    MESSAGE_INFO: 'MessageInfo',
    SEARCH_TAB: 'SearchTab',
    CALLS_TAB: 'CallsTab',
    CALLS: 'Calls',
    CALL_INFO: 'CallInfo',
    CALL_DETAIL: 'CallDetail',
    EXPENSE_DETAILS: 'ExpenseDetails',
    RECURRING_BILLS: 'RecurringBills',
    GROUP_STATS: 'GroupStats',
    ASK_AI: 'AskAi',
    BILL_SPLIT: 'BillSplit',
    SETTINGS: 'Settings',
    NOTIFICATION_SETTINGS: 'NotificationSettings',
    AI_INDEX: 'AiIndex',
    PROFILE: 'Profile',
    CHAT_MEDIA_GALLERY: 'ChatMediaGallery',
    FILE_PREVIEW: 'FilePreview',
    STARRED_MESSAGES: 'StarredMessages',
  },
} as const;
