/**
 * Recurring pattern detection (ai_layer/docs/26).
 *
 * Deterministic clustering over a group's expense history — NO FM call, no
 * network. Finds "Netflix ₹649 around the 5th, three months running" shaped
 * patterns so the app can offer "make this recurring?" instead of demanding
 * manual setup. Pure + unit-tested; surfaces: AddExpense inline chip, stats
 * insight card, and the memory-ledger commitments fact.
 */

import type { Expense } from '@/models';

export interface RecurringCandidate {
    /** Stable cluster key — the normalized title. */
    key: string;
    /** Display title from the most recent occurrence. */
    title: string;
    category: string;
    /** Median amount across occurrences (the prefill amount). */
    medianAmount: number;
    /** All amounts within ±25% of the median → suggest a FIXED bill; else variable. */
    amountStable: boolean;
    cadence: 'weekly' | 'monthly';
    /** Monthly cadence: modal day-of-month of the occurrences. */
    dayOfMonth?: number;
    /** Weekly cadence: modal weekday (0 = Sunday). */
    weekday?: number;
    occurrenceCount: number;
    lastAt: number;
    /** Most frequent payer across occurrences. */
    paidBy: string;
    /** Participant ids from the most recent occurrence. */
    participantIds: string[];
}

const DAY_MS = 24 * 60 * 60 * 1000;
const MIN_OCCURRENCES = 3;
const AMOUNT_TOLERANCE = 0.25;
/** A pattern is "alive" if its last occurrence is within 1.5 cadence periods. */
const LIVENESS_FACTOR = 1.5;

/** Lowercase, strip emoji/punctuation, collapse whitespace. */
export const normalizeTitleKey = (title: string): string =>
    title
        .toLowerCase()
        .replace(/[\p{Extended_Pictographic}\p{Emoji_Component}]/gu, '')
        .replace(/[^\p{L}\p{N}\s]/gu, ' ')
        .replace(/\s+/g, ' ')
        .trim();

const median = (values: number[]): number => {
    const sorted = [...values].sort((a, b) => a - b);
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
};

const mode = <T,>(values: T[]): T => {
    const counts = new Map<T, number>();
    let best = values[0];
    let bestCount = 0;
    for (const value of values) {
        const count = (counts.get(value) ?? 0) + 1;
        counts.set(value, count);
        if (count > bestCount) {
            best = value;
            bestCount = count;
        }
    }
    return best;
};

const cadenceFromGapDays = (gapDays: number): 'weekly' | 'monthly' | null => {
    if (gapDays >= 5.5 && gapDays <= 8.5) return 'weekly';
    if (gapDays >= 26 && gapDays <= 35) return 'monthly';
    return null;
};

/**
 * Detect recurring-looking clusters in an expense list.
 *
 * Rules: ≥3 same-title occurrences; median inter-occurrence gap matches a
 * weekly or monthly cadence; pattern still alive (last occurrence within 1.5
 * periods of `now`). Expenses already generated by a bill (`expense.
 * recurring` metadata) never cluster, and `excludeKeys` (existing bill
 * titles) suppresses already-set-up patterns.
 */
export const detectRecurringCandidates = (
    expenses: Expense[],
    options?: { now?: number; excludeKeys?: Iterable<string> },
): RecurringCandidate[] => {
    const now = options?.now ?? Date.now();
    const excluded = new Set([...(options?.excludeKeys ?? [])].map(normalizeTitleKey));

    const clusters = new Map<string, Expense[]>();
    for (const expense of expenses) {
        if (expense.recurring) continue;
        const key = normalizeTitleKey(expense.title ?? '');
        if (!key || excluded.has(key)) continue;
        const bucket = clusters.get(key);
        if (bucket) bucket.push(expense);
        else clusters.set(key, [expense]);
    }

    const candidates: RecurringCandidate[] = [];
    for (const [key, cluster] of clusters) {
        if (cluster.length < MIN_OCCURRENCES) continue;
        const ordered = [...cluster].sort((a, b) => a.createdAt - b.createdAt);

        const gaps: number[] = [];
        for (let i = 1; i < ordered.length; i++) {
            gaps.push((ordered[i].createdAt - ordered[i - 1].createdAt) / DAY_MS);
        }
        // Same-day duplicates (split receipts, corrections) are not a cadence.
        const realGaps = gaps.filter((gap) => gap >= 1);
        if (realGaps.length < MIN_OCCURRENCES - 1) continue;

        const medianGap = median(realGaps);
        const cadence = cadenceFromGapDays(medianGap);
        if (!cadence) continue;

        const periodDays = cadence === 'weekly' ? 7 : 30.4;
        const last = ordered[ordered.length - 1];
        if (now - last.createdAt > periodDays * LIVENESS_FACTOR * DAY_MS) continue;

        const amounts = ordered.map((e) => e.amount);
        const medianAmount = median(amounts);
        const amountStable =
            medianAmount > 0 &&
            amounts.every((a) => Math.abs(a - medianAmount) <= medianAmount * AMOUNT_TOLERANCE);

        candidates.push({
            key,
            title: last.title,
            category: last.category ?? 'Other',
            medianAmount: Math.round(medianAmount * 100) / 100,
            amountStable,
            cadence,
            ...(cadence === 'monthly'
                ? { dayOfMonth: mode(ordered.map((e) => new Date(e.createdAt).getDate())) }
                : { weekday: mode(ordered.map((e) => new Date(e.createdAt).getDay())) }),
            occurrenceCount: ordered.length,
            lastAt: last.createdAt,
            paidBy: mode(ordered.map((e) => e.paidBy)),
            participantIds: last.participants.map((p) => p.userId),
        });
    }

    return candidates.sort((a, b) => b.occurrenceCount - a.occurrenceCount || b.lastAt - a.lastAt);
};

/** Match a just-typed expense title against detected candidates. */
export const matchCandidate = (
    title: string,
    candidates: RecurringCandidate[],
): RecurringCandidate | undefined => {
    const key = normalizeTitleKey(title);
    if (!key) return undefined;
    return candidates.find((c) => c.key === key);
};
